version: "3"

services:
    database:
        image: docker.io/bitnami/postgresql:13
        container_name: marketplace-data
        ports:
            - 127.0.0.1:5432:5432
        volumes:
            - marketplace-data:/bitnami/postgresql
            - ./.docker/db:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_DB=marketplace
            - POSTGRES_PASSWORD=pa55w0rd
    discovery-server:
        image: catalincaprita/discovery-server:latest
        ports:
            - 8761:8761

    buyer-service:
        image: catalincaprita/buyer-service:latest
        container_name: buyer-service
        ports:
            -   127.0.0.1:8080:8080
        depends_on:
            -   discovery-server
            -   database
        environment:
            DBMS_HOST: database
            DISCOVERY_HOST: discovery-server
            OWNER_URL: owner-service
    buyer-web:
        image: catalincaprita/buyer-app:latest
        container_name: buyer-web
        ports:
            -   3000:3000

    owner-service:
        image: catalincaprita/owner-service:latest
        container_name: owner-service
        ports:
            - 127.0.0.1:8081:8081
        depends_on:
            - discovery-server
            - database
        environment:
            DBMS_HOST: database
            DISCOVERY_HOST: discovery-server
            BUYER_URL: buyer-service
    owner-web:
        image: catalincaprita/owner-app:latest
        container_name: owner-web
        ports:
            - 3001:3000

volumes:
    marketplace-data:
