server:
  tomcat:
    uri-encoding: UTF-8
  port:
    8081
spring:
  application:
    name: owner-service
  main:
    banner-mode: "off"
    allow-circular-references: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    url: jdbc:postgresql://${DBMS_HOST:localhost}:5432/owner
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: pa55w0rd

# Spring Cloud Netflix-Eureka Client Configurations
eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    eureka-server-port: 8761
internal:
  buyerUrl: ${BUYER_URL:localhost}


